spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.93:8848
        group: gulimall
      config:
        server-addr: 192.168.31.93:8848
        file-extension: yaml
        namespace: gulimall
        group: dev